# Generated by Django 4.1.7 on 2023-03-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="cover_photo",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
    ]
