# Generated by Django 4.1.7 on 2023-03-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cover_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/cover_photos"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/profile_pictures"
            ),
        ),
    ]
